version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - mongodb
    env_file:
      - ./.env
    container_name: visa_bot
  mongodb:
    image: mongo:4.4.18
    restart: always
    env_file:
      - ./.env
    volumes: 
      - dbdata:/data/db
    ports:
      - '27018:27017'
    container_name: visa_mongo
  npm:
    image: node:18
    working_dir: /app
    entrypoint: [ "npm" ]
    volumes:
      - ./:/app

volumes:
  dbdata:
